spring.application.name=tasktimetracker

spring.datasource.url=jdbc:postgresql://localhost:5432/task_time_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.jackson.serialization.write-dates-as-timestamps=false

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=ru.testcdek.tasktimetracker.model
mybatis.configuration.map-underscore-to-camel-case=true

server.port=8080